apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-http-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.citrixIngressGateway.label | default "citrix-ingressgateway" }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
