apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-http-gateway
  - bookinfo-https-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /
    route:
    - destination:
        host: productpage
---
